#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

#of2306
. /usr/lib/openfoam/openfoam2306/etc/bashrc

# Setting the number of utilized cores
export OMP_NUM_THREADS=4  # Replace '4' with the desired number of threads

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# Removing old mesh
rm -f log.tetrahedralMesh 
rm -f log.checkMesh 
rm -f log.foamToVTK
rm -f log.paraFoam
rm -rf constant/polyMesh 
rm -rf VTK

# Update the user with the status - spinner goes after 
echo "===========================================================>>>"
echo "Mesh is being crafted, please hang on... " & 
echo
# build the mesh in tetrahedral mode 
tetMesh > log.tetrahedralMesh & 
wait
echo "Mesh is successfully generated!" &

# Extract ClockTime value from log.tetrahedralMesh
clock_time=$(grep "ClockTime =" log.tetrahedralMesh | awk '{print $7}' | tr -d '[:alpha:]')
sleep_time=$((clock_time + 1))

#sleep 4 # FLAG! hard coded: that needs to be read from the mesh file as time_mesh + 2s 
sleep $sleep_time # FLAG! hard coded: that needs to be read from the mesh file as time_mesh + 2s 

# Saving the mesh in VTK format (for CAD viewers)
##wait
##runApplication foamToVTK 
wait
runApplication paraFoam   

echo "Checking mesh quality..." &
wait
runApplication checkMesh 
echo "Mesh quality checked! Click on 'Load mesh quality' to view the report."
echo
echo "===========================================================<<<"
#------------------------------------------------------------------------------
