#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
#. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# Define a spinner to entertain the user while the mesh is being created
spinner() {
  local pid=$1
  local delay=0.1
  local spinstr='|/-\'
  while ps -p $pid > /dev/null; do
    local temp=${spinstr#?}
    printf " [%c]  " "$spinstr"
    local spinstr=$temp${spinstr%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done
  printf "    \b\b\b\b"
}

#source ~/.bashrc 
##of2306
#. /usr/lib/openfoam/openfoam2306/etc/bashrc
#of11
. /opt/openfoam11/etc/bashrc

# Removing old solution 
foamListTimes -rm

rm log.*
rm -r dynamicCode
rm -r postProcessing
rm -r 0

foamDictionary system/controlDict -entry writeFormat -set ascii

#runApplication blockMesh
#runApplication extrudeMesh

# Creating the initialization directory
cp -r 0.orig/ 0
setFields

#foamDictionary system/decomposeParDict -entry numberOfSubdomains -set 6
#decomposePar -force

#mpirun -np 6 compressibleInterFoam -parallel > out-mediumMesh-MS-parallel6procs.dat & 
compressibleInterFoam > log.compressibleInterFoam & 
tail -10f log.compressibleInterFoam  

##tail -10f log  && foamMonitor -l postProcessing/residuals/0/residuals.da

#sleep 2

#foamMonitor -l postProcessing/residuals/0/residuals.dat 
#------------------------------------------------------------------------------
