#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#-----------------------------------------------------

#rm -rf 0
#cp -r 0.orig 0
rm -rf log.decomposePar log.simpleFoam log.pimpleFoam log.reconstructParMesh log.potentialFoam log.renumberMesh
runApplication decomposePar -force
touch case.foam
runParallel renumberMesh -overwrite

runParallel potentialFoam
runParallel simpleFoam
