#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

# of2306
. /usr/lib/openfoam/openfoam2306/etc/bashrc

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
#------------------------------------------------------------------------------

restore0Dir

# Convert mesh from resources directory
runApplication star4ToFoam -scale 1 \
    "$FOAM_TUTORIALS"/resources/geometry/nacaAirfoil/nacaAirfoil

# Symmetry plane -> empty
sed -i -e 's/symmetry\([)]*;\)/empty\1/' constant/polyMesh/boundary

# Don't need these extra files (from star4ToFoam conversion)
rm -f \
   constant/cellTable \
   constant/polyMesh/cellTableId \
   constant/polyMesh/interfaces  \
   constant/polyMesh/origCellId  \
   ;

runApplication checkMesh

if isParallel "$@"
then

    runApplication decomposePar

    runParallel $(getApplication)

else

    runApplication $(getApplication)

fi

#------------------------------------------------------------------------------
